# Site settings
title: To Appease My Hunger
email: knight.w.fu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Doing math by the seat of my pants
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blog.knightfu.com" # the base hostname & protocol for your site
github_username:  evilwire
version: 1

# Build settings
markdown: kramdown
# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'Gemfile'] # files to exclude
